name: path_sam3
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.7.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - certifi==2025.11.12
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - decord==0.6.0
      - einops==0.8.1
      - fairscale==0.4.13
      - filelock==3.19.1
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - ftfy==6.1.1
      - fvcore==0.1.5.post20221221
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.5
      - hydra-core==1.3.2
      - idna==3.11
      - imageio==2.37.2
      - iopath==0.1.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - pandas==2.3.3
      - pillow==11.3.0
      - portalocker==3.2.0
      - protobuf==6.33.1
      - pycocotools==2.0.10
      - pyparsing==3.2.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - safetensors==0.7.0
      - sam3==0.1.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - shellingham==1.5.4
      - sniffio==1.3.1
      - socksio==1.0.0
      - submitit==1.5.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.10.16
      - timm==1.0.22
      - torch==2.7.0+cu126
      - torchaudio==2.7.0+cu126
      - torchmetrics==1.8.2
      - torchvision==0.22.0+cu126
      - tqdm==4.67.1
      - triton==3.3.0
      - typer-slim==0.20.0
      - tzdata==2025.2
      - werkzeug==3.1.4
      - yacs==0.1.8
      - zstandard==0.25.0
